GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order Pizza"
}

###

DELETE http://localhost:3001/todo/delete/650c08830f84cbfadd85fda0

###

PUT http://localhost:3001/todo/complete/650c036e71a8648817ae4bc8